// Automatically generated by astro-icon
// 1b1098e6e9cc304303607d2b9794dfd021d60fea373fa8265e834af7571c53b1

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "linkedin"
		| "telegram";
}